//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



/** 标牌明细 */
export interface BatchDetailDto {
    printDto?: PrintDto;
    batch?: BatchDto;
    test?: TestDto;
    /** 物理信息 */
    physicses?: PhysicsDto[] | undefined;
}

/** 标牌管理 */
export interface BatchDto {
    /** 标牌Id */
    batchId?: string | undefined;
    /** 批号 */
    batchNo?: string | undefined;
    /** 规格 */
    specification?: string | undefined;
    /** 牌号 */
    brand?: string | undefined;
    /** 定尺 */
    length?: number;
    /** 公称质量 */
    weight?: number;
    /** 质检员 */
    quality?: string | undefined;
    /** 计量员 */
    metrologists?: string | undefined;
    /** 创建时间 */
    createTime?: Date;
}

export interface BatchDtoPagedResultDto {
    page?: PageInfo;
    items?: BatchDto[] | undefined;
}

/** 标牌管理 */
export interface CreateBatchDto {
    /** 标牌Id */
    batchId?: string | undefined;
    /** 批号 */
    batchNo?: string | undefined;
    /** 规格 */
    specification?: string | undefined;
    /** 牌号 */
    brand?: string | undefined;
    /** 定尺 */
    length?: number;
}

/** 创建组织 */
export interface CreateOuDto {
    /** 组织Id */
    ouId?: string | undefined;
    /** 组织名称 */
    name?: string | undefined;
    /** 电话 */
    phone?: string | undefined;
    /** 地址 */
    address?: string | undefined;
    /** 上级Id */
    parentId?: string | undefined;
    ouType?: OuType;
}

/** 物理 */
export interface CreatePhysicsDto {
    /** 标牌Id */
    batchId?: string | undefined;
    /** 物理Id */
    physicsId?: string | undefined;
    /** 钢种 */
    type?: string | undefined;
    /** 规格 */
    specification?: string | undefined;
    /** 面积 */
    area?: string | undefined;
    /** 标距长度 */
    length?: string | undefined;
    /** 屈服点负荷N */
    yieldPointLoad?: number;
    /** 抗拉强度 */
    tensileStrength?: number;
    /** 实测屈服强度ReL */
    reL?: number;
    /** 实测抗拉强度Rm */
    rm?: number;
    /** 实测强屈比Rm/ReL */
    rm_ReL?: number;
    /** ReL/ReL */
    reL_ReL?: number;
    /** 断后伸长率 */
    elongation?: number;
    /** 最大力总伸长率 */
    forceElongation?: number;
    /** 冷弯试验 */
    coldBendingTest?: string | undefined;
}

/** 打印 */
export interface CreatePrintDto {
    /** 打印Id */
    printId?: string | undefined;
    /** 标牌Id */
    batchId?: string | undefined;
    /** 支数 */
    count?: number;
    /** 公称质量 */
    weight?: number;
    /** 质检员 */
    quality?: string | undefined;
    /** 计量员 */
    metrologists?: string | undefined;
}

/** 化学 */
export interface CreateTestDto {
    /** 碳 */
    c?: number;
    /** 锰 */
    mn?: number;
    /** 硅 */
    si?: number;
    /** 磷 */
    p?: number;
    /** 硫 */
    s?: number;
    /** 铬 */
    cr?: number;
    /** 镍 */
    ni?: number;
    /** 钼 */
    mo?: number;
    /** 铜 */
    cu?: number;
    /** 钒 */
    v?: number;
    /** 标牌Id */
    batchId?: string | undefined;
}

/** CreateUserDto */
export interface CreateUserDto {
    /** 用户Id */
    userId?: string | undefined;
    /** 用户名 */
    userName?: string | undefined;
    /** 姓名 */
    name?: string | undefined;
    /** 手机号码 */
    phoneNumber?: string | undefined;
    /** 身份证号 */
    idNo?: string | undefined;
    userType?: UserType;
    /** 党员类型 */
    readonly userTypeDesc?: string | undefined;
    /** 组织Id */
    ouId?: string | undefined;
    /** 职务 */
    position?: string | undefined;
    positionType?: PositionType;
    /** 职务 */
    readonly positionTypeDesc?: string | undefined;
    /** 角色 */
    roles?: string[] | undefined;
    /** 密码 */
    password?: string | undefined;
}

export interface GenerateInput {
    name: string;
    readonly camelCaseName?: string | undefined;
    displayName?: string | undefined;
    moduleName?: string | undefined;
    moduleDisplayName?: string | undefined;
    namespace?: string | undefined;
    fields?: ModelField[] | undefined;
}

/** 标牌管理 */
export interface GetBatchListInput {
    /** 批号 */
    batchNo?: string | undefined;
    page?: PageInfo;
    /** 排序 */
    sorting?: string | undefined;
}

export interface GetOuListInput {
    /** 上级Id */
    parentId?: string | undefined;
    page?: PageInfo;
}

/** 物理 */
export interface GetPhysicsListInput {
    /** 标牌Id */
    batchId: string;
    page?: PageInfo;
    /** 排序 */
    sorting?: string | undefined;
}

/** 打印 */
export interface GetPrintListInput {
    /** 批次Id */
    batchId: string;
    page?: PageInfo;
    /** 排序 */
    sorting?: string | undefined;
}

/** GetRoleListInput */
export interface GetRoleListInput {
    page?: PageInfo;
}

/** 化学 */
export interface GetTestListInput {
    /** 标牌Id */
    batchId: string;
    page?: PageInfo;
    /** 排序 */
    sorting?: string | undefined;
}

/** GetUserListInput */
export interface GetUserListInput {
    /** 用户名 */
    userName?: string | undefined;
    page?: PageInfo;
    /** 分页 */
    sorting?: string | undefined;
}

/** 用户信息 */
export interface IdentityModel {
    /** 用户Id */
    userId?: string | undefined;
    /** 用户名 */
    userName?: string | undefined;
    /** 姓名 */
    name?: string | undefined;
    /** 组织Id */
    ouId?: string | undefined;
    /** 是否超管 */
    isSpecial?: boolean;
    positionType?: PositionType;
}

/** 登录模型 */
export interface LoginModel {
    /** 用户名 */
    userName?: string | undefined;
    /** 密码 */
    password?: string | undefined;
    /** 记住我 */
    isPersistent?: boolean;
}

export interface LoginResult {
    /** token */
    accessToken?: string | undefined;
    /** 过期时间 */
    expireIn?: number;
}

export interface ModelField {
    name?: string | undefined;
    readonly camelCaseName?: string | undefined;
    displayName?: string | undefined;
    type?: string | undefined;
    isPrimaryKey?: boolean;
    canBeNull?: boolean;
    isQuery?: boolean;
    isDto?: boolean;
    isCreate?: boolean;
    isUpdate?: boolean;
}

/** 组织Dto */
export interface OuDto {
    /** 组织Id */
    ouId?: string | undefined;
    /** Id */
    readonly id?: string | undefined;
    /** 组织名称 */
    name?: string | undefined;
    /** 电话 */
    phone?: string | undefined;
    /** 地址 */
    address?: string | undefined;
    /** 上级Id */
    parentId?: string | undefined;
    ouType?: OuType;
    /** 组织级别 */
    readonly ouTypeDesc?: string | undefined;
    /** 子列表 */
    children?: OuDto[] | undefined;
}

export interface OuDtoPagedResultDto {
    page?: PageInfo;
    items?: OuDto[] | undefined;
}

export enum OuType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
}

export interface PageInfo {
    pageIndex?: number;
    pageSize?: number;
    totalCount?: number;
    totalPage?: number;
}

export interface PermissionDto {
    /** 名称 */
    name?: string | undefined;
    /** 显示名称 */
    displayName?: string | undefined;
    /** 父级名称 */
    parent?: string | undefined;
    /** 是否选中 */
    isSelected?: boolean;
}

/** 物理 */
export interface PhysicsDto {
    /** 标牌Id */
    batchId?: string | undefined;
    /** 物理Id */
    physicsId?: string | undefined;
    /** 钢种 */
    type?: string | undefined;
    /** 规格 */
    specification?: string | undefined;
    /** 面积 */
    area?: string | undefined;
    /** 标距长度 */
    length?: string | undefined;
    /** 屈服点负荷N */
    yieldPointLoad?: number;
    /** 抗拉强度 */
    tensileStrength?: number;
    /** 实测屈服强度ReL */
    reL?: number;
    /** 实测抗拉强度Rm */
    rm?: number;
    /** 实测强屈比Rm/ReL */
    rm_ReL?: number;
    /** ReL/ReL */
    reL_ReL?: number;
    /** 断后伸长率 */
    elongation?: number;
    /** 最大力总伸长率 */
    forceElongation?: number;
    /** 冷弯试验 */
    coldBendingTest?: string | undefined;
}

export interface PhysicsDtoPagedResultDto {
    page?: PageInfo;
    items?: PhysicsDto[] | undefined;
}

export enum PositionType {
    _0 = 0,
    _1 = 1,
}

/** 打印 */
export interface PrintDto {
    /** 打印Id */
    printId?: string | undefined;
    /** 标牌Id */
    batchId?: string | undefined;
    /** 支数 */
    count?: number;
    /** 公称质量 */
    weight?: number;
    /** 质检员 */
    quality?: string | undefined;
    /** 计量员 */
    metrologists?: string | undefined;
    /** 创建时间 */
    createTime?: Date;
}

export interface PrintDtoPagedResultDto {
    page?: PageInfo;
    items?: PrintDto[] | undefined;
}

/** 打印数据模型 */
export interface PrintModelDto {
    /** Json */
    json?: string | undefined;
    /** 数据 */
    data?: string | undefined;
}

/** 角色 */
export interface RoleDto {
    /** 角色Id */
    roleId?: string | undefined;
    /** 角色名称 */
    name?: string | undefined;
    /** 角色描述 */
    description?: string | undefined;
    /** 角色权限 */
    rolePermissions?: string[] | undefined;
}

export interface RoleDtoPagedResultDto {
    page?: PageInfo;
    items?: RoleDto[] | undefined;
}

/** 化学 */
export interface TestDto {
    /** 碳 */
    c?: number;
    /** 锰 */
    mn?: number;
    /** 硅 */
    si?: number;
    /** 磷 */
    p?: number;
    /** 硫 */
    s?: number;
    /** 铬 */
    cr?: number;
    /** 镍 */
    ni?: number;
    /** 钼 */
    mo?: number;
    /** 铜 */
    cu?: number;
    /** 钒 */
    v?: number;
    /** Ceq */
    ceq?: number;
    /** 标牌Id */
    batchId?: string | undefined;
}

export interface TestDtoPagedResultDto {
    page?: PageInfo;
    items?: TestDto[] | undefined;
}

/** 标牌管理 */
export interface UpdateBatchDto {
    /** 标牌Id */
    batchId?: string | undefined;
    /** 批号 */
    batchNo?: string | undefined;
    /** 规格 */
    specification?: string | undefined;
    /** 牌号 */
    brand?: string | undefined;
    /** 定尺 */
    length?: number;
}

/** 物理 */
export interface UpdatePhysicsDto {
    /** 标牌Id */
    batchId?: string | undefined;
    /** 物理Id */
    physicsId?: string | undefined;
    /** 钢种 */
    type?: string | undefined;
    /** 规格 */
    specification?: string | undefined;
    /** 面积 */
    area?: string | undefined;
    /** 标距长度 */
    length?: string | undefined;
    /** 屈服点负荷N */
    yieldPointLoad?: number;
    /** 抗拉强度 */
    tensileStrength?: number;
    /** 实测屈服强度ReL */
    reL?: number;
    /** 实测抗拉强度Rm */
    rm?: number;
    /** 实测强屈比Rm/ReL */
    rm_ReL?: number;
    /** ReL/ReL */
    reL_ReL?: number;
    /** 断后伸长率 */
    elongation?: number;
    /** 最大力总伸长率 */
    forceElongation?: number;
    /** 冷弯试验 */
    coldBendingTest?: string | undefined;
}

/** 打印 */
export interface UpdatePrintDto {
    /** 打印Id */
    printId?: string | undefined;
    /** 标牌Id */
    batchId?: string | undefined;
    /** 支数 */
    count?: number;
    /** 公称质量 */
    weight?: number;
    /** 质检员 */
    quality?: string | undefined;
    /** 计量员 */
    metrologists?: string | undefined;
}

/** 化学 */
export interface UpdateTestDto {
    /** 碳 */
    c?: number;
    /** 锰 */
    mn?: number;
    /** 硅 */
    si?: number;
    /** 磷 */
    p?: number;
    /** 硫 */
    s?: number;
    /** 铬 */
    cr?: number;
    /** 镍 */
    ni?: number;
    /** 钼 */
    mo?: number;
    /** 铜 */
    cu?: number;
    /** 钒 */
    v?: number;
    /** 标牌Id */
    batchId?: string | undefined;
}

/** FileResult */
export interface UploadResult {
    /** 文件地址 */
    url?: string | undefined;
}

export interface UserDto {
    /** 用户Id */
    userId?: string | undefined;
    /** 用户名 */
    userName?: string | undefined;
    /** 姓名 */
    name?: string | undefined;
    /** 手机号码 */
    phoneNumber?: string | undefined;
    /** 身份证号 */
    idNo?: string | undefined;
    userType?: UserType;
    /** 党员类型 */
    readonly userTypeDesc?: string | undefined;
    /** 组织Id */
    ouId?: string | undefined;
    /** 职务 */
    position?: string | undefined;
    positionType?: PositionType;
    /** 职务 */
    readonly positionTypeDesc?: string | undefined;
    /** 角色 */
    roles?: string[] | undefined;
}

export interface UserDtoPagedResultDto {
    page?: PageInfo;
    items?: UserDto[] | undefined;
}

export enum UserType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
}

export interface FileParameter {
    data: any;
    fileName: string;
}